server:
  error:
    include-message: always
  port: 8099
  servlet:
    context-path: /team-assignments
  forward-headers-strategy: native

spring:
  datasource:
    url: jdbc:derby:team-assignments-db;create=true;collation=TERRITORY_BASED:PRIMARY
  jpa:
    database-platform: org.hibernate.dialect.DerbyTenSevenDialect
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: docs/sql/ddl.sql
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          client-id: 207575990260-i1u73321tnitbteokktvb9gic9tigrjl.apps.googleusercontent.com